projeto/Controllers/ProdutosController.cs
using projeto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projeto.Controllers
{
    public class ProdutosController : Controller
    {
        // GET: Produtos
        public ActionResult Index(int? id)
        {
           
            string teste = Request.RawUrl;
            List<Models.Produtos> produtos = new List<Models.Produtos>();
            int totalPorPagina = 15;
            int totalPaginas = 0;
            int pagina = 0;

            if (id == null)
                pagina = 1;
            else
                pagina = Convert.ToInt32(id);

            if (Request.Form.Count > 0)
            {

                string parametroBusca = Request.Form["tbPesquisa"].ToString();

                if (!string.IsNullOrEmpty(parametroBusca))
                {
                    Produtos prod = new Produtos();
                    produtos = prod.SelecionarProdutos(parametroBusca);
                }

            }
            else {

                Produtos prod = new Produtos();
                produtos = prod.SelecionarProdutos("");
            }


            int resto = produtos.Count % totalPorPagina;
            totalPaginas = produtos.Count / totalPorPagina;

            if (resto > 0)
                totalPaginas++;

            ViewBag.TotalPaginas = totalPaginas;

            

            return View(produtos.Skip((pagina - 1) * 15).Take(15).ToList());
        }

      
   }
}

projeto/Controllers/UploadController.cs
using projeto.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projeto.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }

        public FileResult Dowload()
        {
            string contentType = "application/txt";
            return File("~/Arquivos/erros/erros-importacao.csv", contentType, "erros.txt");
        }

        public ActionResult ResumoImportacao(List<ResumoImportacao> listaResumo)
        {
           return View(listaResumo);
        }

        public ActionResult Upload(HttpPostedFileBase Files)
        {
            string mensagem = string.Empty;

            // Verifica se o usuário selecionou algum arquivo
            if (Files != null && Files.ContentLength > 0)
            {               
                // Extrai apenas o nome do arquivo
                var fileName = Path.GetFileName(Files.FileName);
                // Armazena o arquivo dentro da pasta ~/Arquivo
                var path = Path.Combine(Server.MapPath("~/Arquivos"), fileName);              

                Importacao imp = new Importacao();
                imp.Info.NomeArquivo =path;

                if (imp.validaArquivo())
                {
                    if (!imp.verifcaJaImportou(path))
                    {
                        Files.SaveAs(path);
                        imp.Info.DataImportacao = DateTime.Now;
                        imp.inserirImportacao();
                        imp.processaImportacao();
                        List<ResumoImportacao> erros = imp.ResumoImportacao;
                        mensagem = imp.Mensagem;
                        imp = null;

                        if (erros[0].QuantidadeErros > 0)
                            ViewBag.Erros = "Sim";
                        else
                            ViewBag.Erros = "Não";

                        return View("ResumoImportacao",erros);
                    }
                    else
                    {
                        mensagem = "O arquivo já foi importado";
                        ViewBag.Mensagem = mensagem;
                        imp = null;
                        return View("Index");
                    }
                }
                else
                {
                    mensagem = imp.Mensagem;
                    ViewBag.Mensagem=mensagem;
                    imp = null;
                    return View("Index");
                }

            }
            else
            {
                mensagem = "Nenhum arquivo foi selecionado";
                return View("Index");
            }

            
        }
    }
}

projeto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Projeto xl", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Visualizar Produtos", "Index", "Produtos", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Novo arquivo", "Index", "Upload", new { area = "" }, new { @class = "navbar-brand" })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>